theme: jekyll-theme-midnight
title: [Bargul]
description: [Play as Bargul, a wise magician struggling to save his ancient artifacts from a meteor shower.]

show_downloads: true
google_analytics: "UA-109596642-1"
